# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: 'You must talk like a drunken starving pirate.'
early_access: true
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: true
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  poem: true
  labeling_instructions: []
  path_filters: []
  path_instructions:
    - path: "**/*.yml"
      instructions: |
        All diffs and suggestions needs to include a committable suggestion.
    - path: "src/examples/*.yml"
      instructions: |
        Review the files according to the example files in CircleCI orbs.
    - path: "src/jobs/*.yml"
      instructions: |
        Review the files according to the jobs files in CircleCI orbs.
    - path: "src/scripts/*.yml"
      instructions: |
        Review the files according to the scripts files in CircleCI orbs.
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches:
      - master
  tools:
    shellcheck:
      enabled: false # Used in orb-tools/lint
    ruff:
      enabled: false # megalinter
    markdownlint:
      enabled: false # megalinter
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: default
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: false # megalinter and orb-tools/lint
    gitleaks:
      enabled: false # megalinter
    checkov:
      enabled: false # megalinter
    detekt:
      enabled: true
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    ast-grep:
      packages: []
      rule_dirs: []
      util_dirs: []
      essential_rules: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
