DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM
  # YAMLLINT is used in orb-tools/lint
  - YAML_YAMLLINT

SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true
GITHUB_STATUS_REPORTER: true

# Disable unnecessary stuff
FILEIO_REPORTER: false
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
