DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
