description: >
  This executor runs MegaLinter with cupcake flavor in a Docker container.
  It is useful for running MegaLinter in a CI/CD pipeline.
  MegaLinter is a tool that helps you maintain code quality by automatically
  running linters and formatters on your codebase.



parameters:
  resource_class:
    type: string
    default: medium
    description: |
      The resource class to use for the jobs.
      See list of resource classes here:
      https://circleci.com/docs/2.0/configuration-reference/#resource_class
  tag:
    type: string
    default: latest
    description: |
      Choose a specific tag of megalinter:
      https://hub.docker.com/r/oxsecurity/megalinter/tags
  flavor:
    type: string
    default: ""
    description: |
      Choose a specific flavor of megalinter:
      https://megalinter.io/latest/flavors/
      Pull Requests are welcome to add more flavors!
